WgInterface:
  eth: eth0
  # dir is the place where configuration files of wg are located.
  dir: /etc/wireguard/
  udpPort: 51820

GrpcConfig:
  domain:
    endpoint: localhost
    port: 5353
  tls:
    enabled: false
    cert-file:
    cert-key:
    ca-file:
    directory:
  auth:
    aKey: deneme
    sKey: test